expected:
  type: unordered
  vals:
  - \[.+?hart#\d+\s*\]
  - type: ordered
    vals:
    - Hello Jrinx, I am master hart!
    - 'enable virtual memory \(satp: [0-9a-zA-Z]{16}\)'
    - Hello Jrinx, I am slave hart!
    - '<<< [a-zA-Z]+-test begin'
    - '>>> [a-zA-Z]+-test end'
    - arg-driven test done, halt!
unexpected:
  type: unordered
  vals:
  - 'assertion failed:'
