name: Regression Test

on: [push]

env:
  CROSS_COMPILE: riscv64-linux-gnu-

jobs:
  regression-test:
    runs-on: ubuntu-latest
    container:
      image: coekjan/jrinx-devel:latest
    strategy:
      matrix:
        mode: [debug, release]
        board: [virt, sifive_u]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - run: git config --system --add safe.directory "$GITHUB_WORKSPACE"
      - name: Run Test
        env:
          COMPILE_MODE: ${{ matrix.mode }}
          BOARD: ${{ matrix.board }}
        run: |
          ./scripts/run-tests -p
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: logs-${{ matrix.mode }}-${{ matrix.board }}
          path: logs/*.log
